### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by qadzek** [klangman/Adjacent-Windows#1]
I guess it's best to move the discussion from my feature request in the Linux Mint [repo](https://github.com/orgs/linuxmint/discussions/311) to here.

I have been using the extension for the past week and it's working pretty well, except for the (previously mentioned) problem of sometimes skipping over a window when there are 3 or more windows open and I manually selected one.

I just noticed that you added a new algorithm, so I changed to setting to "Closest with a visible corner". I will let you know how that goes.

Thanks again for creating this extension!

**Comment by klangman** [comment]
Thanks for the feedback.. After pushing the "Closest with a visible corner" algorithm I found some cases where it didn't work right, so I am working on a new approach, which its self seems to have some holes. In any case I am slowly adding code to hopefully land in a place where it works like people would intuitively expect.

I plan on replacing the "Closest with a visible corner" option with whatever I land on in the end. This algorithm might be too complex to describe in 4 or 5 words so I will likely name it something along the lines of "Smart" or "Hybrid".

**Comment by klangman** [comment]
I have been playing around with a number of different approaches on how to best select the next window but I always end up finding deficiencies in the behaviour when not using tiling but just having windows overlapping in random ways. I think I am just being overly picky and I need to settle on a "good enough" approach.

I have also added optional hotkeys for "Under" (switch to the next window in the z-order that the current window is overlapping to some degree) and "Undo" which will restore the windows that were previously activated. I have yet to commit these change but they will be part of the next commit.

I have to do more testing with more then one monitor attached. My normal setup is with one large monitor. I'll try and recreate the issue you pointed out.

I do intend to push the applet to cinnamon-spices when I have completed the above work and you and I agree it's working reasonably well with the set of features currently implemented.

Thanks for the feedback and for the help with testing!!

**Comment by klangman** [comment]
@qadzek I just pushed my latest updates. I hope the changes to the "Closest with a visible corner" algorithm makes it perform better in more difficult scenarios. It also has the "Under" and "Undo" hotkeys that I talked about in my last comment. Let me know what you think.

I didn't yet do any more testing with 2 monitors so I suspect the bug you reported is still there. I'll do more testing this week with the two monitor setup I have at work.

**Comment by klangman** [comment]
I was unable to see any issues with how it works in multi-monitor setups. I suspect that the odd window selection you observed has more to do with the algorithm. Maybe now with the updates I pushed yesterday it will not happen anymore?

**Comment by klangman** [comment]
Yes, I think it's close now.. I'll do more testing and wait for you to have some more time to test. If all is well by Sunday then I might push to cinnamon-spices at that time.

I also have to consider if I should just remove the Closest/Highest-Z-Order options since it's likely they won't get used much if at all.

I am also considering adding some options to control some algorithm parameters like:
1. Allowing some minor corner obscuring and still allow a window to be marked as a candidate (i.e. 0-30 pixels)
2. Allowing setting a minimum directional overlap restriction before giving the candidate a priority boost (i.e. 0-30 percent)

As for building this into Cinnamon.. Not sure if the maintainers would want this built-in or not, but I am fine with that happening. I would even be willing to look at making the changes myself. I'll propose it when I push to cinnamon-spices. In any case this extension will be useful for people running Mint 21.3 and older (or any other distro that are running Cinnamon 6.0.4 or older, or what ever release the changes makes it into).

**Comment by klangman** [comment]
The extension is now now cinnamon-spices.  https://cinnamon-spices.linuxmint.com/extensions/view/99
